### ISSUE TITLE
Fix error with JCS cache in Analytic UI demo

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#764]
Closing the Analytic UI REST service causes an error to be thrown which causes the cache to be empty - this means that Named Operations / Analytics etc don't persist between REST API boots.

It looks as though two versions of the ServletLifecycleListener are running. By removing the following line from the web.xml this problem seems to go away:
```xml
    <listener>
        <listener-class>uk.gov.gchq.gaffer.rest.ServletLifecycleListener</listener-class>
    </listener>
```
However, once this is removed it hits another problem. A ClassDefNotFoundError is thrown. This does not happen with the standard UI and so looks like a problem with the analytic-rest project.

**Comment by d47853** [comment]
Update:

To fix this issue, just delete the src/main/webapp directory from the analytics-rest project. These files are inherited from the parent.

**Comment by n288TJYRX** [comment]
Done in pull request #766. Just waiting to be merged.

**Comment by d47853** [comment]
Looks like for whatever reason, removing the file didn't work. Still getting the following error:
```
disk.indexed.IndexedDiskCache ERROR  - Region [JobTracker] Error occurred during defragmentation.
java.io.IOException: Mismatched memory and disk length (1397245252) for [DED:  pos = 1321 len = 1331]
        at org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDisk.move(IndexedDisk.java:138)
        at org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache.defragFile(IndexedDiskCache.java:1332)
        at org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache.optimizeFile(IndexedDiskCache.java:1257)
        at org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache.disposeInternal(IndexedDiskCache.java:1094)
        at org.apache.commons.jcs.auxiliary.disk.indexed.IndexedDiskCache$1.run(IndexedDiskCache.java:1040)
        at java.lang.Thread.run(Thread.java:748)
gaffer.rest.ServletLifecycleListener INFO  - Server shutting down - releasing resources

```

**Comment by n3101** [comment]
The Analytic UI was removed by #971 so this can also be closed.
